### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by JoeyK4816**

### CODE REVIEW

**Review by JoshLucio — APPROVED** [review]

**Comment by JoeyK4816** [comment]
@JoshLucio 

Its been changed a bit since you last reviewed, please look it over again.

**Review by pdewey — APPROVED** [review]
Approved assuming it has been QA'd.

**Comment by JoeyK4816** [comment]
Its live on QA right now. I'm awaiting feedback from the customer to see if anything else needs to be done before I merge this in and release a new version.

**Review by JoshLucio — APPROVED** [review]

**Comment by JoshLucio** [comment]
I got some new tickets about this bug, I made a fix, then found that Joey already made the same fix, so approved and merging now.

**Comment by JoeyK4816** [comment]
Still being useful, long after I'm gone.

**Pull request merged**
